### ISSUE TITLE
Fixing document

### ISSUE THREAD

**Issue by frederett** [dromtek/vel#1]
Hello~~

I found some typo on README.md and CONTRIBUTING, 
- In How To Run section, the command to run bot should use `DISCORD_TOKEN_BOT` rather `TOKEN` for environment variable.
- Change filename of CONTRIBUTING to CONTRIBUTING.md and align the path to contributing page on how to contributing section in README.md.

If you interested, ping me so I will assign it to you.

**Comment by Aryangp** [comment]
hi assign this issue to me pls i can solve this

**Comment by frederett** [comment]
@Aryangp sure thing.
